server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ilzhgmhrctzqhm:4dd69f7d2265e7c64352ff1396c51dbadb12331427806c5b9589046922d406f4@ec2-34-193-112-164.compute-1.amazonaws.com:5432/d550sbukbuvr1u
    username: ilzhgmhrctzqhm
    password: 4dd69f7d2265e7c64352ff1396c51dbadb12331427806c5b9589046922d406f4
jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  hibernate:
    ddl-auto: none
application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
